.eslintrc
package.json
src/parser.js
test/test.js

also fixed idiosyncrasies in the code

fixed eslint and added it to testing process

---

test/test.js

switched to toEqual from toBe

---

src/parser.js
test/test.js

fixes #6 
@eventualbuddha is this looking good is there anything I'm missing?

added modulo compilation

---

src/parser.js
test/test.js

Argument destructuring

---

src/parser.js
test/test.js

added basic try expressions

---

.eslintrc
src/parser.js
test/test.js

Separate transpiler

---

src/parser.js
test/test.js

fixed return statements

---

src/parser.js
test/test.js

added throw statements

---

src/parser.js
test/test.js

added class properties

---

package.json
src/parser.js
test/test.js

Static class properties

---

package.json
src/parser.js
test/test.js

Fix return in else body

---

bin/decaf
example/example.coffee
example/example.js
package.json
test/test.js

- color output
- replace option

Improve cli

---

src/parser.js
test/test.js

For in destructuring

---

src/parser.js
test/test.js

Fix class methods

---

src/parser.js
test/test.js

so far we only used ranges as values, but they can also be expressions

range expressions

---

src/parser.js
test/test.js

Compound assignments

---

src/parser.js
test/test.js

prevent automatic return statement insertion into constructors

---

src/parser.js
test/test.js

destructuring with @

---

src/parser.js
test/test.js

Classes with comments

---

src/parser.js
test/test.js

Fix if else blocks

---

src/parser.js
test/test.js

Fix the case where there is a conditionless switch w/ else

---

src/parser.js
test/test.js

Assign bound functions to object

---

package.json
src/parser.js
test/test.js

Fix last throw statement

---

src/parser.js
test/test.js

Fix mulitiline strings

---

src/parser.js
test/test.js

FIxing static class properties

---

test/test.js

#101 already fixed, just adding spec

---

src/parser.js
test/test.js

added method and specs for detecting illegal super calls in constructors

---

package.json
src/parser.js
test/test.js

Wrap unnamed class expressions

---

src/parser.js
test/test.js

Fixes conditional for loop

---

test/test.js

fixed #102
It was already fixed, I just added a spec

Fix class attribute expression

---

src/parser.js
test/test.js

Change let declaration in for loop back to var

---

src/parser.js
test/test.js

Pass arguments to constructor

---

src/parser.js
test/test.js

Pass arguments super

---

package.json
src/parser.js
test/test.js

fixes #120
fixes #136 
fixes #128

Fix break statements, double variable declarations, and conditional expressions

---

src/parser.js
test/test.js

fixes ** operator

---

src/parser.js
test/test.js

Should fix #147.  All credit to @lemonmade for this.

Bound methods fix

---

src/parser.js
test/test.js

Again, all credit goes to @lemonmade.

Fix this in soaks/ existence expressions (#6)

---

src/parser.js
test/test.js

Fix `unless list.includes(foo)`

---

readme.md

The build status SVG was appearing as a broken image.

Fix build status SVG link & rebrand links

---

bin/decaf
test/test.js

It should probably not exit with status code 0

exit with staus code 1 if decaf fails
